# Generated by Django 6.0.3 on 2026-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0016_video_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="video_suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
