# Generated by Django 6.0.3 on 2026-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_enable_x"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="enable_tiktok",
            field=models.BooleanField(default=True),
        ),
    ]
