# Generated by Django 6.0.3 on 2026-05-17 15:42

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0018_s3_upload_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="visual_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediagroup",
            name="type",
            field=core.fields.TruncatingCharField(
                choices=[
                    ("product", "Product"),
                    ("manual", "Manual"),
                    ("generated", "Generated"),
                    ("general", "General"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
