"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-_xd9@pg$npr23(8dwldi%tt)ppao#fgc9c35qqa9cqqo_r!=qq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://*.stryng.io', 'http://localhost:8000', 'http://localhost:8100']

# Trust the X-Forwarded-Proto header set by reverse proxies (e.g. nginx/Caddy)
# so Django and allauth build https:// callback URLs correctly.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ─── ngrok (local development only) ──────────────────────────────────────────
# Set NGROK_URL in .env (e.g. https://abc123.ngrok-free.app) to tunnel OAuth
# callbacks to localhost. Has no effect when the variable is absent (production).
NGROK_URL = os.environ.get('NGROK_URL', '').rstrip('/')
if NGROK_URL:
    CSRF_TRUSTED_ORIGINS.append(NGROK_URL)
    # Trust X-Forwarded-Host so request.build_absolute_uri() returns the ngrok URL.
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django_cotton',
    'django_q',
    'django_eventstream',
    'credits',
    'projects',
    'integrations',
    'brand',
    'social_media',
    'scheduler',
    'media_library',
    'home',
    'accounts',
    'django_cleanup.apps.CleanupConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.usersessions',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'anymail',
    'mjml',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'allauth.usersessions.middleware.UserSessionsMiddleware',
    'projects.middleware.ProjectMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'projects.context_processors.project_context',
                'credits.context_processors.credits_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'stryng'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Media)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ─── S3 / Object Storage ─────────────────────────────────────────────────────
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '') or None
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False

_USE_S3 = bool(AWS_STORAGE_BUCKET_NAME)

STORAGES = {
    "default": (
        {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {"location": "media"},
        }
        if _USE_S3
        else {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        }
    ),
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'

# Authentication
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.SocialAccountAdapter'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# django-allauth
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        },
    },
}

# ─── Email ────────────────────────────────────────────────────────────────────

EMAIL_BACKEND = 'anymail.backends.amazon_ses.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@stryng.io')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

ANYMAIL = {
    'AMAZON_SES_CLIENT_PARAMS': {
        'region_name': os.environ.get('AWS_SES_REGION_NAME', AWS_S3_REGION_NAME),
        'aws_access_key_id': AWS_ACCESS_KEY_ID,
        'aws_secret_access_key': AWS_SECRET_ACCESS_KEY,
    },
}

# ─── MJML ─────────────────────────────────────────────────────────────────────
MJML_BACKEND_MODE = 'cmd'
MJML_EXEC_CMD = str(BASE_DIR.parent / 'bin' / 'mjml')

# ─── Stripe ──────────────────────────────────────────────────────────────────
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICING_TABLE_ID = os.environ.get('STRIPE_PRICING_TABLE_ID', '')

# ─── Credits ─────────────────────────────────────────────────────────────────
CREDITS_SIGNUP_GRANT = int(os.environ.get('CREDITS_SIGNUP_GRANT', '50'))
CREDITS_SIGNUP_DAYS = int(os.environ.get('CREDITS_SIGNUP_DAYS', '30'))

# ─── Django Q2 ───────────────────────────────────────────────────────────────
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 6,
    'timeout': 300,
    'retry': 360,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
    'catch_up': False,  # Skip missed runs to avoid backlog on startup
}

# ─── Cache ───────────────────────────────────────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f"redis://{os.environ.get('REDIS_HOST', 'redis')}:{os.environ.get('REDIS_PORT', '6379')}/1",
    }
}

# ─── Django Eventstream ───────────────────────────────────────────────────────
EVENTSTREAM_CHANNELMANAGER_CLASS = 'social_media.channelmanager.MessageChannelManager'
EVENTSTREAM_REDIS = {
    'host': os.environ.get('REDIS_HOST', 'redis'),
    'port': int(os.environ.get('REDIS_PORT', 6379)),
    'db': 0,
}

# ─── Site / Campaign agents ───────────────────────────────────────────────────
# Public-facing base URL — used by agents to build absolute media URLs.
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')
# Unsplash API access key — https://unsplash.com/developers
UNSPLASH_ACCESS_KEY = os.environ.get('UNSPLASH_ACCESS_KEY', '')
# Firecrawl webhook shared secret — verify inbound webhook requests
FIRECRAWL_WEBHOOK_SECRET = os.environ.get('FIRECRAWL_WEBHOOK_SECRET', '')

# ─── Authlib OAuth Clients (for integrations app) ──────────────────────
AUTHLIB_OAUTH_CLIENTS = {
    'facebook': {
        'client_id': os.environ.get('FACEBOOK_APP_ID', ''),
        'client_secret': os.environ.get('FACEBOOK_APP_SECRET', ''),
        'access_token_url': 'https://graph.facebook.com/v22.0/oauth/access_token',
        'authorize_url': 'https://www.facebook.com/v22.0/dialog/oauth',
        'api_base_url': 'https://graph.facebook.com/v22.0/',
        'client_kwargs': {
            'scope': 'pages_show_list pages_manage_posts pages_read_engagement',
            'token_endpoint_auth_method': 'client_secret_post',
        },
    },
    'instagram': {
        'client_id': os.environ.get('INSTAGRAM_CLIENT_ID', ''),
        'client_secret': os.environ.get('INSTAGRAM_CLIENT_SECRET', ''),
        'access_token_url': 'https://api.instagram.com/oauth/access_token',
        'authorize_url': 'https://api.instagram.com/oauth/authorize',
        'api_base_url': 'https://graph.instagram.com/v22.0/',
        'client_kwargs': {
            'scope': 'instagram_business_basic instagram_business_content_publish',
            'token_endpoint_auth_method': 'client_secret_post',
        },
    },
    'linkedin': {
        'client_id': os.environ.get('LINKEDIN_CLIENT_ID', ''),
        'client_secret': os.environ.get('LINKEDIN_CLIENT_SECRET', ''),
        'access_token_url': 'https://www.linkedin.com/oauth/v2/accessToken',
        'authorize_url': 'https://www.linkedin.com/oauth/v2/authorization',
        'api_base_url': 'https://api.linkedin.com/',
        'client_kwargs': {
            'scope': 'r_basicprofile w_organization_social w_member_social rw_organization_admin r_organization_social r_organization_social_feed r_organization_followers w_organization_social_feed w_member_social_feed r_1st_connections_size',
            'token_endpoint_auth_method': 'client_secret_post',
        },
    },
    'tiktok': {
        'client_id': os.environ.get('TIKTOK_CLIENT_KEY', ''),
        'client_secret': os.environ.get('TIKTOK_CLIENT_SECRET', ''),
        'access_token_url': 'https://open.tiktokapis.com/v2/oauth/token/',
        'authorize_url': 'https://www.tiktok.com/v2/auth/authorize/',
        'api_base_url': 'https://open.tiktokapis.com/v2/',
        'client_kwargs': {
            'scope': 'user.info.basic,video.upload,video.publish',
            'token_endpoint_auth_method': 'client_secret_post',
        },
    },
}

# Dotted paths to provider classes loaded by the integrations registry
INTEGRATION_PROVIDERS = [
    'integrations.providers.facebook.FacebookProvider',
    'integrations.providers.instagram.InstagramProvider',
    'integrations.providers.linkedin.LinkedInProvider',
    'integrations.providers.tiktok.TikTokProvider',
]

# Media files (uploads)
MEDIA_URL = '/media/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'allauth': {'handlers': ['console'], 'level': 'DEBUG'},
        'requests': {'handlers': ['console'], 'level': 'DEBUG'},
    },
}
MEDIA_ROOT = BASE_DIR / 'media'